'use client'

/* eslint-disable react/no-unescaped-entities */
import React from 'react';
import styles from '@/app/css/404.module.css';
import Link from 'next/link';

export const metadata = {
    title: 'Kasa - Error 404',
    description: 'Generated by create next app',
  }

function error() {
  return (
    <div id={styles.page404}>
      <h1 className={styles.error404}>404</h1>
      <p className={styles.sentence404}>Oups! La page que vous demandez n'existe pas.</p>
      <Link className={styles.link404} href="/">Retourner sur la page d'accueil</Link>
    </div>
  );
}

export default error;
