import React from 'react'
import Banner from '../components/Banner'
import Collapse from '../components/Collapse'
import styles from '@/app/css/About.module.css'
import {aboutText} from '@/public/data/a_propos'

export const metadata = {
  title: 'Kasa - A propos',
  description: 'Generated by create next app',
}

const page = () => {
  const landscapeAbout = '/images/landscape_about.png'

  return (
    <div id={styles.about}>
      <Banner type="base" image={landscapeAbout} />

      <div className={styles.collapse_about}>
        {aboutText.map((collapse) => (
          <Collapse
            key={collapse.title}
            title={collapse.title}
            text={collapse.description}
          />
        ))}
      </div>
    </div>
  )
}

export default page